# Generated by Django 6.0.4 on 2026-04-18 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Original title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime'), ('cartoon', 'Cartoon'), ('documentary', 'Documentary'), ('other', 'Other')], default='movie', max_length=20, verbose_name='Media type')),
                ('status', models.CharField(choices=[('announced', 'Announced'), ('ongoing', 'Ongoing'), ('released', 'Released'), ('archived', 'Archived')], default='released', max_length=20, verbose_name='Status')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='Release year')),
                ('season_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Season')),
                ('episode_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Episode')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (min)')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Genres')),
                ('countries', models.JSONField(blank=True, default=list, verbose_name='Countries')),
                ('language', models.CharField(blank=True, max_length=64, verbose_name='Language')),
                ('age_rating', models.CharField(blank=True, max_length=16, verbose_name='Age rating')),
                ('quality', models.CharField(blank=True, max_length=32, verbose_name='Quality')),
                ('video_codec', models.CharField(blank=True, max_length=32, verbose_name='Video codec')),
                ('audio_codec', models.CharField(blank=True, max_length=32, verbose_name='Audio codec')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='File')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File size')),
                ('source_path', models.CharField(blank=True, max_length=500, verbose_name='Source path')),
                ('checksum', models.CharField(blank=True, max_length=128, verbose_name='Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Media file',
                'verbose_name_plural': 'Media files',
                'ordering': ('title', 'season_number', 'episode_number'),
                'indexes': [models.Index(fields=['media_type', 'status'], name='media_libra_media_t_03604c_idx'), models.Index(fields=['release_year'], name='media_libra_release_488dde_idx'), models.Index(fields=['title'], name='media_libra_title_752b61_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'season_number', 'episode_number', 'file'), name='unique_media_entry')],
            },
        ),
    ]
