# Generated by Django 6.0.4 on 2026-04-18 17:52

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description_localizations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Description localizations'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='title_localizations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Title localizations'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=media_library.models.media_file_upload_to, verbose_name='File'),
        ),
    ]
