# Generated by Django 6.0.4 on 2026-05-13 12:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_genres_to_relations(apps, schema_editor):
    MediaTitle = apps.get_model("media_library", "MediaTitle")
    Genre = apps.get_model("media_library", "Genre")
    MediaTitleGenre = apps.get_model("media_library", "MediaTitleGenre")

    for media_title in MediaTitle.objects.all().iterator():
        genre_names = media_title.genres
        if not isinstance(genre_names, list):
            continue

        seen = set()
        for name in genre_names:
            if not isinstance(name, str):
                continue
            name = name.strip()
            key = name.casefold()
            if not name or key in seen:
                continue
            seen.add(key)

            genre = Genre.objects.filter(name__iexact=name).first()
            if genre is None:
                genre = Genre.objects.create(name=name)
            MediaTitleGenre.objects.get_or_create(
                media_title=media_title,
                genre=genre,
            )


def migrate_relations_to_genres(apps, schema_editor):
    MediaTitle = apps.get_model("media_library", "MediaTitle")

    for media_title in MediaTitle.objects.all().iterator():
        media_title.genres = list(
            media_title.genre_links.select_related("genre")
            .order_by("genre__name")
            .values_list("genre__name", flat=True)
        )
        media_title.save(update_fields=["genres"])


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MediaTitleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_title_links', to='media_library.genre', verbose_name='Genre')),
                ('media_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_links', to='media_library.mediatitle', verbose_name='Media title')),
            ],
            options={
                'verbose_name': 'Media title genre',
                'verbose_name_plural': 'Media title genres',
                'ordering': ('media_title', 'genre__name'),
            },
        ),
        migrations.RunPython(
            migrate_genres_to_relations,
            migrate_relations_to_genres,
        ),
        migrations.RemoveField(
            model_name='mediatitle',
            name='genres',
        ),
        migrations.AddField(
            model_name='mediatitle',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='media_titles', through='media_library.MediaTitleGenre', to='media_library.genre', verbose_name='Genres'),
        ),
        migrations.AddIndex(
            model_name='mediatitlegenre',
            index=models.Index(fields=['media_title', 'genre'], name='media_libra_media_t_4b31a4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatitlegenre',
            index=models.Index(fields=['genre', 'media_title'], name='media_libra_genre_i_755b83_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediatitlegenre',
            constraint=models.UniqueConstraint(fields=('media_title', 'genre'), name='unique_media_title_genre'),
        ),
    ]
