# Generated by Django 6.0.4 on 2026-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediafile_description_localizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='audio_tracks',
            field=models.JSONField(blank=True, default=list, verbose_name='Audio tracks'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='subtitle_tracks',
            field=models.JSONField(blank=True, default=list, verbose_name='Subtitle tracks'),
        ),
    ]
