# Generated by Django 6.0.4 on 2026-04-18 18:43

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_mediafile_audio_tracks_mediafile_subtitle_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('poster', 'Poster'), ('backdrop', 'Backdrop'), ('screenshot', 'Screenshot'), ('thumbnail', 'Thumbnail'), ('other', 'Other')], default='screenshot', max_length=20, verbose_name='Image type')),
                ('image', models.ImageField(upload_to=media_library.models.media_image_upload_to, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_library.mediafile', verbose_name='Media file')),
            ],
            options={
                'verbose_name': 'Media image',
                'verbose_name_plural': 'Media images',
                'ordering': ('image_type', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['media_file', 'image_type'], name='media_libra_media_f_e251c4_idx'), models.Index(fields=['is_primary'], name='media_libra_is_prim_b91ffb_idx')],
            },
        ),
    ]
