# Generated by Django 6.0.4 on 2026-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_restructure_media_library'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediavariant',
            name='variant_has_single_parent',
        ),
        migrations.RenameIndex(
            model_name='mediaimage',
            new_name='media_libra_media_t_5eba72_idx',
            old_name='media_libra_media_t_90551e_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaimage',
            new_name='media_libra_is_prim_b91ffb_idx',
            old_name='media_libra_is_prim_8b2270_idx',
        ),
        migrations.RenameIndex(
            model_name='mediatitle',
            new_name='media_libra_media_t_334cb9_idx',
            old_name='media_libra_media_t_39857b_idx',
        ),
        migrations.RenameIndex(
            model_name='mediatitle',
            new_name='media_libra_release_d7c382_idx',
            old_name='media_libra_release_a0857b_idx',
        ),
        migrations.RenameIndex(
            model_name='mediatitle',
            new_name='media_libra_title_9c5793_idx',
            old_name='media_libra_title_3f16cc_idx',
        ),
        migrations.RenameIndex(
            model_name='mediavariant',
            new_name='media_libra_title_i_12d27c_idx',
            old_name='media_libra_title_9281f4_idx',
        ),
        migrations.RenameIndex(
            model_name='mediavariant',
            new_name='media_libra_episode_7154e3_idx',
            old_name='media_libra_episode_eb6c12_idx',
        ),
        migrations.AddConstraint(
            model_name='mediavariant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('title__isnull', False), ('episode__isnull', True)), models.Q(('title__isnull', True), ('episode__isnull', False)), _connector='OR'), name='variant_has_single_parent'),
        ),
    ]
