# Generated by Django 6.0.4 on 2026-04-19 00:55

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0006_align_restructure_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavariant',
            name='playable_error',
            field=models.TextField(blank=True, verbose_name='Playable error'),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='playable_file',
            field=models.FileField(blank=True, upload_to=media_library.models.playable_variant_upload_to, verbose_name='Playable file'),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='playable_file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Playable file size'),
        ),
    ]
