# Generated by Django 6.0.4 on 2026-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0007_mediavariant_playable_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediavariant',
            name='hls_error',
            field=models.TextField(blank=True, verbose_name='HLS error'),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='hls_manifest',
            field=models.CharField(blank=True, max_length=500, verbose_name='HLS manifest'),
        ),
    ]
