# Generated by Django 6.0.4 on 2026-04-19 01:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0008_mediavariant_hls_error_mediavariant_hls_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('analyzing', 'Analyzing tracks'), ('extracting_subtitles', 'Extracting subtitles'), ('generating_hls', 'Generating HLS'), ('finished', 'Finished'), ('failed', 'Failed')], default='queued', max_length=40, verbose_name='Stage')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='media_library.mediavariant', verbose_name='Media variant')),
            ],
            options={
                'verbose_name': 'Media processing job',
                'verbose_name_plural': 'Media processing jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='media_libra_status_cba306_idx'), models.Index(fields=['variant', 'status'], name='media_libra_variant_50b354_idx')],
            },
        ),
    ]
